# Site settings
title: DevMa Blog
email: rd.rexma@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  我是一名来自中国的开发者，开始写写博客，里面包含了一些技术内容。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  https://github.com/RexMa88

# Build settings
markdown: kramdown
