# Site settings
title: Developer Ma
header-img: img/home-bg.jpg
email: rd.rexma@gmail.com
description: "Developer Ma Blog"
baseurl: ""
url: "http://wwww.blackaile.com"
github_username:  RexMa88
# zhihu_username:  zhou-geek

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 30
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]



